name: GrossUp
options:
  bundleIdPrefix: com.jaredhilton
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  GrossUp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jaredhilton.GrossUp
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
    sources:
      - GrossUpApp.swift
      - GrossUpView.swift
      - Assets.xcassets
  GrossUpTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jaredhilton.GrossUpTests
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - GrossUpTests.swift
    dependencies:
      - target: GrossUp
