name: GrossUp
options:
  bundleIdPrefix: com.jaredhilton
settings:
  base:
    SWIFT_VERSION: 6.0
targets:
  GrossUp:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jaredhilton.GrossUp
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: S863LZ43ZG
    sources:
      - GrossUpApp.swift
      - GrossUpView.swift
      - Assets.xcassets
  GrossUpTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jaredhilton.GrossUpTests
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - GrossUpTests.swift
    dependencies:
      - target: GrossUp
